### ISSUE TITLE
Spyglass displays check need an update.

### ISSUE THREAD

**Issue by Alex715** [AsYetUntitled/Framework#451]
### Expected behaviour
Detect display who have been modified in memory.

### Actual behaviour
 The detection of modifieds displays is buggy, every displays will return modified but is not.

### Steps to reproduce the behaviour
Play with spyglass running.

----

mission version : 5.0

Game version: 1.82

Branch: main / beta branch not specified

**Comment by Jawshy** [comment]
@Alex715, thanks for the bug report. Are there any SpyGlass messages in the arma3.rpt or arma3server.rpt log files?

**Comment by Alex715** [comment]
Yes, 
"SPYGLASS-FLAG: NAME : UID : Modified_Method_RscDisplayMainMap"

with the code below is exactly the same as _onLoad but arma return me is not the same.

`_onLoad = getText(configFile >> "RscDisplayInventory" >> "onLoad");

if (_onLoad != "[""onLoad"",_this,""RscDisplayInventory"",'IGUI'] call 	(uinamespace getvariable 'BIS_fnc_initDisplay')") exitWith {
	hint format ["%1",_onLoad];
};`

**Comment by Leigham** [comment]
you should be able to close this now.

**Comment by Jawshy** [comment]
Resolved in https://github.com/AsYetUntitled/Framework/pull/436.

**Comment by Alex715** [comment]
Not fixed for me, output are different.

"onLoad : [""onLoad"",_this,""RscDiary"",'GUI'] call 	(uinamespace getvariable 'BIS_fnc_initDisplay')
expectedOnLoad : [""onLoad"",_this,""RscDiary"",'GUI'] call  (uiNamespace getVariable 'BIS_fnc_initDisplay')"
